### ISSUE TITLE
Error when running "sudo make install"

### ISSUE THREAD

**Issue by ayykamp** [anonymix007/libldacdec#4]
`$ sudo make install
ln -sf libldacdec.so libldacdec.so.1
cp -a libldacdec.so libldacdec.so.1 /usr/lib/
cp libldacBT_dec.h /usr/include/ldac/libldacBT_dec.h
cp: cannot create regular file '/usr/include/ldac/libldacBT_dec.h': No such file or directory
make: *** [Makefile:48: install] Error 1`

**Comment by anonymix007** [comment]
```console
sudo mkdir /usr/include/ldac
```
will do. Or just remove line 48 from Makefile.
