### ISSUE TITLE
unable to configure bluealsa-aplay to properly stereo

### ISSUE THREAD

**Issue by viktory36** [anonymix007/libldacdec#5]
hey, i've wired a 3.5mm left/right splitter to 2 speakers on my pi, and set everything up as in the readme. I'm unable to play anything through bluetooth where the 2 channels are clearly separate - for example when only right channel is supposed to sound, i hear sound thru both speakers, but the right one is louder, and vice versa.
when i play a file with aplay 2channeltest.wav or speaker-test -c 2, it sounds correct - when left channel is supposed to sound the right speaker doesn't do anything as desired.

please nelp me config my setup correctly to work in bluetooth?
issue persists on ldac/aac/sbc

**Comment by viktory36** [comment]
sharing some logs,

```
pi@raspberrypi:~ $ bluealsa-aplay --mixer-name=PCM -v
bluealsa-aplay: [893] I: ../../../utils/aplay/aplay.c:1151: Selected configuration:
  BlueALSA service: org.bluealsa
  ALSA PCM device: default
  ALSA PCM buffer time: 500000 us
  ALSA PCM period time: 100000 us
  ALSA mixer device: default
  ALSA mixer element: 'PCM',0
  Bluetooth device(s): ANY
  Profile: A2DP
bluealsa-aplay: [893] D: ../../../utils/aplay/aplay.c:846: Creating IO worker 18:4E:16:77:27:C6
bluealsa-aplay: [893] D: ../../../utils/aplay/aplay.c:1194: Starting main loop
bluealsa-aplay: [894] D: ../../../utils/aplay/aplay.c:514: Opening BlueALSA source PCM: /org/bluealsa/hci0/dev_18_4E_16_77_27_C6/a2dpsnk/source
bluealsa-aplay: [894] D: ../../../utils/aplay/aplay.c:540: Starting IO loop
bluealsa-aplay: [894] D: ../../../utils/aplay/aplay.c:664: Opening ALSA playback PCM: name=default channels=2 rate=96000
bluealsa-aplay: [894] D: ../../../utils/aplay/aplay.c:679: Opening ALSA mixer: name=default elem=PCM index=0
bluealsa-aplay: [894] D: ../../../utils/aplay/aplay.c:578: BT device marked as inactive: 18:4E:16:77:27:C6
bluealsa-aplay: [894] D: ../../../utils/aplay/aplay.c:664: Opening ALSA playback PCM: name=default channels=2 rate=96000
bluealsa-aplay: [894] D: ../../../utils/aplay/aplay.c:679: Opening ALSA mixer: name=default elem=PCM index=0
bluealsa-aplay: [894] D: ../../../utils/aplay/aplay.c:578: BT device marked as inactive: 18:4E:16:77:27:C6
...
```

``` 
pi@raspberrypi:~ $ cat /etc/asound.conf
pcm.!default {
        type hw
        card 1
}

ctl.!default {
        type hw
        card 1
}
```

```
pi@raspberrypi:~ $ amixer scontents
Simple mixer control 'PCM',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 15
  Mono:
  Front Left: Playback 15 [100%] [0.00dB] [on]
  Front Right: Playback 15 [100%] [0.00dB] [on]
pi@raspberrypi:~ $ amixer scontrols
Simple mixer control 'PCM',0
```

hardware: pi -> usb dac (card 1) -> 3.5mm left/right splitter -> 2 portable speakers

with all config items looking okay, and playing the same left/right test audio wav file thru `aplay` and then over samsung bluetooth, I'm convinced something is going wrong while keeping the channels separate over bluetooth here.

but im happy to be proven wrong!!

**Comment by anonymix007** [comment]
This is not libldacdec issue if it persists on AAC and SBC as well. You can report it to bluez-alsa.

**Comment by viktory36** [comment]
So this was happening because of my samsung's dolby atmos, and my poweramp's "stereo expand". Had to switch them off.

:)
